name: CI

on:
  push:
    branches:
      - main  # Run CI on every push to the `main` branch
  pull_request:  # Optionally, run CI on pull requests targeting the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pytest

      # Step 4: Run the pipeline script
      - name: Run pipeline
        run: |
          python ./project/pipeline.py

      # Step 5: Run the tests script
      - name: Run tests
        run: |
          python ./project/tests.py
